---
swagger: "2.0"
info:
  description: "This is the pet store application which stores and retrieves pet details."
  version: "0.0.1"
  title: "MyPetStore"
  termsOfService: "http://conatct.com"
  contact:
    name: "Keerthi"
    url: "http://conatct.com"
    email: "keerthikala.prabhu@wipro.com"
  license:
    name: "my license"
    url: "http://mylicense.com"
host: "www.mypetstore.com"
basePath: "/pet"
tags:
- name: "pet"
  description: "Everything about your Pets"
- name: "store"
  description: "Access to Petstore orders"
- name: "user"
  description: "Operations about user"
paths:
  /pet:
    post:
      tags: []
      summary: ""
      description: ""
      operationId: ""
      consumes: []
      produces: []
      parameters: []
      x-swagger-router-controller: "Default"
    options:
      tags: []
      summary: ""
      description: ""
      operationId: ""
      consumes: []
      produces: []
      parameters: []
      x-swagger-router-controller: "Default"
definitions:
  pet:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "pet id"
      category:
        type: "object"
        description: "pet category"
        properties: {}
      name:
        type: "string"
        description: "pet name"
      photoUrls:
        type: "object"
        description: "photoUrls"
        properties: {}
      tags:
        type: "object"
        description: "tags"
        properties: {}
      status:
        type: "string"
        description: "pet status"
